export const GET_BOARD_FAILURE = 'GAME/GET_BOARD_FAILURE';
export const GET_BOARD_SUCCESS = 'GAME/GET_BOARD_SUCCESS';
export const HIDE_LOADER = 'GAME/HIDE_LOADER';
export const SHOW_LOADER = 'GAME/SHOW_LOADER';
